#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")
---
apiVersion: build.tanzu.vmware.com/v1
kind: BuildConfiguration
metadata:
  name: epc
spec:
  availabilityTarget: epc
  caCertificateSecretRefs:
    - name: epc-buildconfiguration-ca-certs
  imageRepositorySecretRefs:
    - name: epc-buildconfiguration-registry-creds
    - name: artifactory-secret-tap-saas
  imageRepositoryTemplate: harbor.elasticsky.cloud/epc/{name}
  egressPointTemplate: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: epc-buildconfiguration-ca-certs
type: Opaque
stringData:
  harbor-cert.pem: #@ data.values.workload.registry.ca_cert
---
apiVersion: v1
kind: Secret
metadata:
  name: epc-buildconfiguration-registry-creds
type: kubernetes.io/dockerconfigjson
data:
  #@ registry_creds = {"username": data.values.workload.registry.username, "password": data.values.workload.registry.password}
  #@ encoded_creds = base64.encode(json.encode({"auths": {data.values.workload.registry.hostname: registry_creds}}))
  .dockerconfigjson: #@ encoded_creds